name: Backend CI 
on: 
  push: 
    paths:
      - "backend/**"
      - ".github/workflows/backend-ci.yml"
  pull_request:
    branches:
      - main
    paths:
      - "backend/**"
      - ".github/workflows/backend-ci.yml"

jobs:
  backend:
    name: Revisar y compilar Backend
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: backend
    
    steps:
      - name: Descargar repositorio
        uses: actions/checkout@v4

      - name: Configurar Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: maven

      - name: Compilar y verificar con Maven
        run: mvn -B verify